dist: trusty
sudo: required
group: beta
language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - npm i -g solc
  - npm i -g truffle
  - npm i -g ganache-cli
  - npm i -g codecov
  - nohup ganache-cli &> /dev/null &

script:
  - truffle compile --network travis
  - truffle migrate --reset --network travis
  - truffle test --network travis

after_script:
  - npm run coverage && cat coverage/lcov.info
  - codecov