dist: trusty
sudo: required
group: beta
language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - npm i -g solc
  - npm i -g truffle
  - npm i -g ethereumjs-testrpc
  - nohup truffle develop --log &> /dev/null &

script:
  - truffle compile
  - truffle migrate --reset
  - truffle test

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls