dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - npm i -g solc
  - npm i -g truffle
  - npm i -g ethereumjs-testrpc
script:
  - truffle compile
  - truffle migrate --reset
  - truffle test